version: "3"
services:
  pytorch:
    build:
      context: ./docker/pytorch
    tty: true
    ports:
      - "8888:8888"
    command: jupyter lab --no-browser --ip=0.0.0.0 --allow-root --LabApp.token=''
    environment:
      - PYTHONPATH=/workspace/pytorch
    volumes:
      - ./data:/workspace/data:cached
      - ./pytorch:/workspace/pytorch:cached
      - ./docker:/workspace/docker:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  pytorch_tsubame:
    build:
      context: ./docker/pytorch_tsubame
      args:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    tty: true
    ports:
      - "8889:8888"
    command: jupyter lab --no-browser --ip=0.0.0.0 --allow-root --LabApp.token=''
    environment:
      - PYTHONPATH=/workspace/pytorch
    volumes:
      - ./data:/workspace/data:cached
      - ./pytorch:/workspace/pytorch:cached
      - ./docker:/workspace/docker:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
